package it.acsoftware.apachesparkmanager.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import it.acsoftware.apachesparkmanager.model.JobEventSchedule;
import it.acsoftware.apachesparkmanager.service.JobEventScheduleLocalServiceUtil;

/**
 * The extended model base implementation for the JobEventSchedule service. Represents a row in the &quot;ApacheSparkManager_JobEventSchedule&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link JobEventScheduleImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see JobEventScheduleImpl
 * @see it.acsoftware.apachesparkmanager.model.JobEventSchedule
 * @generated
 */
public abstract class JobEventScheduleBaseImpl extends JobEventScheduleModelImpl
    implements JobEventSchedule {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a job event schedule model instance should use the {@link JobEventSchedule} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            JobEventScheduleLocalServiceUtil.addJobEventSchedule(this);
        } else {
            JobEventScheduleLocalServiceUtil.updateJobEventSchedule(this);
        }
    }
}
