create table LiOT_Broker (
	brokerId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	name VARCHAR(75) null,
	protocol VARCHAR(75) null,
	url VARCHAR(75) null,
	port VARCHAR(75) null,
	description VARCHAR(75) null,
	type_ VARCHAR(75) null,
	connectionUsername VARCHAR(75) null,
	connectionPassword VARCHAR(75) null,
	topics VARCHAR(75) null,
	customProps VARCHAR(75) null,
	sslEnabled BOOLEAN,
	sslSecret VARCHAR(75) null,
	sslCertificateUUid VARCHAR(75) null,
	startAtStartup BOOLEAN,
	mqttClientId VARCHAR(75) null,
	mqttQos INTEGER,
	mqttCleanSession BOOLEAN,
	kafkaZookeeperHost VARCHAR(75) null,
	kafkaThreadsPerTopic INTEGER,
	kafkaGroupId VARCHAR(75) null
);

create table LiOT_BrokerMessageListener (
	brokerMessageListenerId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	name VARCHAR(75) null,
	description VARCHAR(75) null,
	brokerId LONG,
	topics VARCHAR(75) null,
	type_ VARCHAR(75) null,
	messageBusDestination VARCHAR(75) null
);