package it.acsoftware.apachesparkmanager.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the JobDateSchedule service. Represents a row in the &quot;ApacheSparkManager_JobDateSchedule&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link it.acsoftware.apachesparkmanager.model.impl.JobDateScheduleModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link it.acsoftware.apachesparkmanager.model.impl.JobDateScheduleImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see JobDateSchedule
 * @see it.acsoftware.apachesparkmanager.model.impl.JobDateScheduleImpl
 * @see it.acsoftware.apachesparkmanager.model.impl.JobDateScheduleModelImpl
 * @generated
 */
public interface JobDateScheduleModel extends BaseModel<JobDateSchedule>,
    GroupedModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a job date schedule model instance should use the {@link JobDateSchedule} interface instead.
     */

    /**
     * Returns the primary key of this job date schedule.
     *
     * @return the primary key of this job date schedule
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this job date schedule.
     *
     * @param primaryKey the primary key of this job date schedule
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the job date schedule ID of this job date schedule.
     *
     * @return the job date schedule ID of this job date schedule
     */
    public long getJobDateScheduleId();

    /**
     * Sets the job date schedule ID of this job date schedule.
     *
     * @param jobDateScheduleId the job date schedule ID of this job date schedule
     */
    public void setJobDateScheduleId(long jobDateScheduleId);

    /**
     * Returns the group ID of this job date schedule.
     *
     * @return the group ID of this job date schedule
     */
    @Override
    public long getGroupId();

    /**
     * Sets the group ID of this job date schedule.
     *
     * @param groupId the group ID of this job date schedule
     */
    @Override
    public void setGroupId(long groupId);

    /**
     * Returns the company ID of this job date schedule.
     *
     * @return the company ID of this job date schedule
     */
    @Override
    public long getCompanyId();

    /**
     * Sets the company ID of this job date schedule.
     *
     * @param companyId the company ID of this job date schedule
     */
    @Override
    public void setCompanyId(long companyId);

    /**
     * Returns the user ID of this job date schedule.
     *
     * @return the user ID of this job date schedule
     */
    @Override
    public long getUserId();

    /**
     * Sets the user ID of this job date schedule.
     *
     * @param userId the user ID of this job date schedule
     */
    @Override
    public void setUserId(long userId);

    /**
     * Returns the user uuid of this job date schedule.
     *
     * @return the user uuid of this job date schedule
     * @throws SystemException if a system exception occurred
     */
    @Override
    public String getUserUuid() throws SystemException;

    /**
     * Sets the user uuid of this job date schedule.
     *
     * @param userUuid the user uuid of this job date schedule
     */
    @Override
    public void setUserUuid(String userUuid);

    /**
     * Returns the user name of this job date schedule.
     *
     * @return the user name of this job date schedule
     */
    @AutoEscape
    @Override
    public String getUserName();

    /**
     * Sets the user name of this job date schedule.
     *
     * @param userName the user name of this job date schedule
     */
    @Override
    public void setUserName(String userName);

    /**
     * Returns the create date of this job date schedule.
     *
     * @return the create date of this job date schedule
     */
    @Override
    public Date getCreateDate();

    /**
     * Sets the create date of this job date schedule.
     *
     * @param createDate the create date of this job date schedule
     */
    @Override
    public void setCreateDate(Date createDate);

    /**
     * Returns the modified date of this job date schedule.
     *
     * @return the modified date of this job date schedule
     */
    @Override
    public Date getModifiedDate();

    /**
     * Sets the modified date of this job date schedule.
     *
     * @param modifiedDate the modified date of this job date schedule
     */
    @Override
    public void setModifiedDate(Date modifiedDate);

    /**
     * Returns the schedule name of this job date schedule.
     *
     * @return the schedule name of this job date schedule
     */
    @AutoEscape
    public String getScheduleName();

    /**
     * Sets the schedule name of this job date schedule.
     *
     * @param scheduleName the schedule name of this job date schedule
     */
    public void setScheduleName(String scheduleName);

    /**
     * Returns the chron expression of this job date schedule.
     *
     * @return the chron expression of this job date schedule
     */
    @AutoEscape
    public String getChronExpression();

    /**
     * Sets the chron expression of this job date schedule.
     *
     * @param chronExpression the chron expression of this job date schedule
     */
    public void setChronExpression(String chronExpression);

    /**
     * Returns the params of this job date schedule.
     *
     * @return the params of this job date schedule
     */
    @AutoEscape
    public String getParams();

    /**
     * Sets the params of this job date schedule.
     *
     * @param params the params of this job date schedule
     */
    public void setParams(String params);

    /**
     * Returns the jar name of this job date schedule.
     *
     * @return the jar name of this job date schedule
     */
    @AutoEscape
    public String getJarName();

    /**
     * Sets the jar name of this job date schedule.
     *
     * @param jarName the jar name of this job date schedule
     */
    public void setJarName(String jarName);

    /**
     * Returns the main class of this job date schedule.
     *
     * @return the main class of this job date schedule
     */
    @AutoEscape
    public String getMainClass();

    /**
     * Sets the main class of this job date schedule.
     *
     * @param mainClass the main class of this job date schedule
     */
    public void setMainClass(String mainClass);

    /**
     * Returns the active of this job date schedule.
     *
     * @return the active of this job date schedule
     */
    public Boolean getActive();

    /**
     * Sets the active of this job date schedule.
     *
     * @param active the active of this job date schedule
     */
    public void setActive(Boolean active);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(
        it.acsoftware.apachesparkmanager.model.JobDateSchedule jobDateSchedule);

    @Override
    public int hashCode();

    @Override
    public CacheModel<it.acsoftware.apachesparkmanager.model.JobDateSchedule> toCacheModel();

    @Override
    public it.acsoftware.apachesparkmanager.model.JobDateSchedule toEscapedModel();

    @Override
    public it.acsoftware.apachesparkmanager.model.JobDateSchedule toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
