package it.acsoftware.brokerportlet.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the BrokerMessageListener service. Represents a row in the &quot;LiOT_BrokerMessageListener&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link it.acsoftware.brokerportlet.model.impl.BrokerMessageListenerModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link it.acsoftware.brokerportlet.model.impl.BrokerMessageListenerImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see BrokerMessageListener
 * @see it.acsoftware.brokerportlet.model.impl.BrokerMessageListenerImpl
 * @see it.acsoftware.brokerportlet.model.impl.BrokerMessageListenerModelImpl
 * @generated
 */
public interface BrokerMessageListenerModel extends BaseModel<BrokerMessageListener>,
    GroupedModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a broker message listener model instance should use the {@link BrokerMessageListener} interface instead.
     */

    /**
     * Returns the primary key of this broker message listener.
     *
     * @return the primary key of this broker message listener
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this broker message listener.
     *
     * @param primaryKey the primary key of this broker message listener
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the broker message listener ID of this broker message listener.
     *
     * @return the broker message listener ID of this broker message listener
     */
    public long getBrokerMessageListenerId();

    /**
     * Sets the broker message listener ID of this broker message listener.
     *
     * @param brokerMessageListenerId the broker message listener ID of this broker message listener
     */
    public void setBrokerMessageListenerId(long brokerMessageListenerId);

    /**
     * Returns the group ID of this broker message listener.
     *
     * @return the group ID of this broker message listener
     */
    @Override
    public long getGroupId();

    /**
     * Sets the group ID of this broker message listener.
     *
     * @param groupId the group ID of this broker message listener
     */
    @Override
    public void setGroupId(long groupId);

    /**
     * Returns the company ID of this broker message listener.
     *
     * @return the company ID of this broker message listener
     */
    @Override
    public long getCompanyId();

    /**
     * Sets the company ID of this broker message listener.
     *
     * @param companyId the company ID of this broker message listener
     */
    @Override
    public void setCompanyId(long companyId);

    /**
     * Returns the user ID of this broker message listener.
     *
     * @return the user ID of this broker message listener
     */
    @Override
    public long getUserId();

    /**
     * Sets the user ID of this broker message listener.
     *
     * @param userId the user ID of this broker message listener
     */
    @Override
    public void setUserId(long userId);

    /**
     * Returns the user uuid of this broker message listener.
     *
     * @return the user uuid of this broker message listener
     * @throws SystemException if a system exception occurred
     */
    @Override
    public String getUserUuid() throws SystemException;

    /**
     * Sets the user uuid of this broker message listener.
     *
     * @param userUuid the user uuid of this broker message listener
     */
    @Override
    public void setUserUuid(String userUuid);

    /**
     * Returns the user name of this broker message listener.
     *
     * @return the user name of this broker message listener
     */
    @AutoEscape
    @Override
    public String getUserName();

    /**
     * Sets the user name of this broker message listener.
     *
     * @param userName the user name of this broker message listener
     */
    @Override
    public void setUserName(String userName);

    /**
     * Returns the create date of this broker message listener.
     *
     * @return the create date of this broker message listener
     */
    @Override
    public Date getCreateDate();

    /**
     * Sets the create date of this broker message listener.
     *
     * @param createDate the create date of this broker message listener
     */
    @Override
    public void setCreateDate(Date createDate);

    /**
     * Returns the modified date of this broker message listener.
     *
     * @return the modified date of this broker message listener
     */
    @Override
    public Date getModifiedDate();

    /**
     * Sets the modified date of this broker message listener.
     *
     * @param modifiedDate the modified date of this broker message listener
     */
    @Override
    public void setModifiedDate(Date modifiedDate);

    /**
     * Returns the name of this broker message listener.
     *
     * @return the name of this broker message listener
     */
    @AutoEscape
    public String getName();

    /**
     * Sets the name of this broker message listener.
     *
     * @param name the name of this broker message listener
     */
    public void setName(String name);

    /**
     * Returns the description of this broker message listener.
     *
     * @return the description of this broker message listener
     */
    @AutoEscape
    public String getDescription();

    /**
     * Sets the description of this broker message listener.
     *
     * @param description the description of this broker message listener
     */
    public void setDescription(String description);

    /**
     * Returns the broker ID of this broker message listener.
     *
     * @return the broker ID of this broker message listener
     */
    public long getBrokerId();

    /**
     * Sets the broker ID of this broker message listener.
     *
     * @param brokerId the broker ID of this broker message listener
     */
    public void setBrokerId(long brokerId);

    /**
     * Returns the topics of this broker message listener.
     *
     * @return the topics of this broker message listener
     */
    @AutoEscape
    public String getTopics();

    /**
     * Sets the topics of this broker message listener.
     *
     * @param topics the topics of this broker message listener
     */
    public void setTopics(String topics);

    /**
     * Returns the type of this broker message listener.
     *
     * @return the type of this broker message listener
     */
    @AutoEscape
    public String getType();

    /**
     * Sets the type of this broker message listener.
     *
     * @param type the type of this broker message listener
     */
    public void setType(String type);

    /**
     * Returns the message bus destination of this broker message listener.
     *
     * @return the message bus destination of this broker message listener
     */
    @AutoEscape
    public String getMessageBusDestination();

    /**
     * Sets the message bus destination of this broker message listener.
     *
     * @param messageBusDestination the message bus destination of this broker message listener
     */
    public void setMessageBusDestination(String messageBusDestination);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(
        it.acsoftware.brokerportlet.model.BrokerMessageListener brokerMessageListener);

    @Override
    public int hashCode();

    @Override
    public CacheModel<it.acsoftware.brokerportlet.model.BrokerMessageListener> toCacheModel();

    @Override
    public it.acsoftware.brokerportlet.model.BrokerMessageListener toEscapedModel();

    @Override
    public it.acsoftware.brokerportlet.model.BrokerMessageListener toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
