package it.acsoftware.brokerportlet.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import it.acsoftware.brokerportlet.model.BrokerMessageListener;
import it.acsoftware.brokerportlet.service.BrokerMessageListenerLocalServiceUtil;

/**
 * The extended model base implementation for the BrokerMessageListener service. Represents a row in the &quot;LiOT_BrokerMessageListener&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link BrokerMessageListenerImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see BrokerMessageListenerImpl
 * @see it.acsoftware.brokerportlet.model.BrokerMessageListener
 * @generated
 */
public abstract class BrokerMessageListenerBaseImpl
    extends BrokerMessageListenerModelImpl implements BrokerMessageListener {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a broker message listener model instance should use the {@link BrokerMessageListener} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            BrokerMessageListenerLocalServiceUtil.addBrokerMessageListener(this);
        } else {
            BrokerMessageListenerLocalServiceUtil.updateBrokerMessageListener(this);
        }
    }
}
