package it.acsoftware.brokerportlet.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import it.acsoftware.brokerportlet.model.Broker;
import it.acsoftware.brokerportlet.service.BrokerLocalServiceUtil;

/**
 * The extended model base implementation for the Broker service. Represents a row in the &quot;LiOT_Broker&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link BrokerImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see BrokerImpl
 * @see it.acsoftware.brokerportlet.model.Broker
 * @generated
 */
public abstract class BrokerBaseImpl extends BrokerModelImpl implements Broker {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a broker model instance should use the {@link Broker} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            BrokerLocalServiceUtil.addBroker(this);
        } else {
            BrokerLocalServiceUtil.updateBroker(this);
        }
    }
}
